### ISSUE TITLE
Menus overlapping

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#1]
- open public inbox and click on inbox to get the received email.
- here you can see the overlapping in the menu.

![Screenshot_7](https://user-images.githubusercontent.com/13029910/85272070-4e027000-b499-11ea-80bf-6db1ae8a4800.jpg)

**Comment by mail7** [comment]
Dear Kuldeep,

Thanks for using the Mail7 services, as it's not load page proper please reload the web application for avoid this issue.

**Comment by Kuldeep-Chhipa** [comment]
Okay, that's fine.
