### ISSUE TITLE
Related support doc link should available on the relative page

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#10]
All Support doc links should available on the relative page as well so it will be user friendly.
Some suggestions like:
1. Routing Rule support doc link should available on this page as well
2. MX Record Setup
3. Manage Email IDs etc.

It will help the user to get the doc from the same page.

**Comment by mail7** [comment]
Thanks Kuldeep, for your feedback Team is working on it and we will update you when we update all relevant document. for now you may visit Mail7 document form [https://docs.mail7.io/](https://docs.mail7.io/)

**Comment by mail7** [comment]
We Added relative pages links of documents in Dashboard.

**Comment by Kuldeep-Chhipa** [comment]
Hello Mail7, Thanks for adding the related doc links where it required.
