### ISSUE TITLE
Not able to see the API Secret

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#11]
- Go to API Credentials 
- Check the API Secret 
- Not able to check the Secret here only
- User can Copy the Secret 

**Expected:**
- First, allow the user to view the secret then the user can copy the secret.

**Comment by mail7** [comment]
Thanks Kuldeep, for your feedback Team is working on it and we will update you when we added this functionality.

**Comment by mail7** [comment]
Hi Kuldeep, We Developed display APISecret functionality on [Dashboard](https://console.mail7.io/admin/configurations/api-credentials)

**Comment by Kuldeep-Chhipa** [comment]
Hello Mail7 Team,
Now I can see the API Secret on the dashboard 
Thanks.
