### ISSUE TITLE
Mail not populating in inbox when click on unread icon

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#2]
- open any received mail.
- Click on the unread Icon
- At this time not populating the all mail-in inbox.
![Screenshot_1](https://user-images.githubusercontent.com/13029910/85291130-b9f3d100-b4b7-11ea-954f-f643ca0d5443.jpg)

**Comment by Kuldeep-Chhipa** [comment]
@dev team please check the same bug in the private inbox as well.

**Comment by mail7** [comment]
Dear Kuldeep,

Thanks for using mail7 services, our team has resolved this issue.

**Comment by Kuldeep-Chhipa** [comment]
I'm happy to use the Mail7 service and also appreciate the  Mail7 team to resolve the bugs.

Now, the bug has been resolved. 

Thanks, Mail7.
