### ISSUE TITLE
My account not open because of bug:2

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#3]
- first of all, run the[ bug:2 ](https://github.com/Compile7/mail7-bug-tracker/issues/2)all steps
- then click on my account icon
- It's not working.
![Screenshot_2](https://user-images.githubusercontent.com/13029910/85291579-4d2d0680-b4b8-11ea-8e4a-3806a8cb32dd.jpg)

> We can also replicate this issue by the following steps:
- Open any mail from the public inbox
- Now Click on my account icon
- It's not working.

**Comment by mail7** [comment]
Dear Kuldeep,

We resolved bug:2 so you no need to face this issue on [Mail7.io](url) Dashboard.

**Comment by Kuldeep-Chhipa** [comment]
Yes, It has been resolved and working fine.
