### ISSUE TITLE
No tool tips for any icon 

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#4]
- As par the UX improvement part there should add the tooltip for each and every icon to understand the icon functionality before performing it.

![Screenshot_3](https://user-images.githubusercontent.com/13029910/85292120-0e4b8080-b4b9-11ea-81af-c62867fcda75.jpg)

**Comment by mail7** [comment]
Thanks Kuldeep for contribution we updated Tooltip in [Mail7 Dashboard](https://console.mail7.io/)

**Comment by Kuldeep-Chhipa** [comment]
Yes, the tooltip for a relative icon is appearing on the hover.

Good to see the fast response.
