### ISSUE TITLE
Inbox not showing the mail when click on public inbox link after any operation

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#5]
- Open any email
- Click on Public Inbox Link 
- All received mail disappear
- When reloading the page all mail appear again
![Screenshot_4](https://user-images.githubusercontent.com/13029910/85292491-96ca2100-b4b9-11ea-9ebb-e497851bcf23.jpg)

**Comment by mail7** [comment]
Dear Kuldeep,

Mail7 Team is really appreciate your contribution. the team has resolved email rendering issue.

**Comment by Kuldeep-Chhipa** [comment]
Thanks for the appreciation Mail7 Team.

The issue has been verified it is working fine.
