### ISSUE TITLE
Duplicate email received in private inbox

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#7]
- Login to Mail7
- Create unique email id 
- Send test mail on that email id from Gmail
- Switch to the private inbox of Mail7  (Which should already open in second tab)
- Don't refresh the page
- after few second duplicate emails received.

![Screenshot_6](https://user-images.githubusercontent.com/13029910/85309577-6e99ec80-b4d0-11ea-9ed2-6d9d0e953308.jpg)

**Comment by mail7** [comment]
Hi Kuldeep,

We resolved this issue for both [public](https://console.mail7.io/admin/inbox/inbox) and [private](https://console.mail7.io/admin/inbox/private) inboxes.

**Comment by Kuldeep-Chhipa** [comment]
Hello Team Mail7,

Both inbox working fine no duplicate email received.
