### ISSUE TITLE
Email Receive time by default shows 23 Hours ago

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#8]
- Login to Mail7
- Create unique email id
- Send test mail on that email id from Gmail
- Switch to the private inbox of Mail7 (Which should already open in the second tab)
- Don't refresh the page
- After few second duplicate emails received.
- Check the time
- by default, it shows 23 hours age
- After some time it reflects the real receive time. 

![Screenshot_8](https://user-images.githubusercontent.com/13029910/85310081-2f1fd000-b4d1-11ea-97b5-17370045999a.jpg)

**Comment by mail7** [comment]
Kuldeep! We fixed this issue in Mail7 and now its working file for Inboxes.

**Comment by Kuldeep-Chhipa** [comment]
Thanks for the quick response and resolve the issue, now it's working fine.
