### ISSUE TITLE
Wrong message when generate email id with existing name

### ISSUE THREAD

**Issue by Kuldeep-Chhipa** [Compile7/mail7-bug-tracker#9]
- Go to **Manage Email IDs** 
- Click on Generate new id
- Enter id **test** and Generate
- Click on Generate new id again
- this time enter the **test** again
- Click on Generate
**Issue:**
- Success message Appears like `Email ID has been updated.`
**Expected:**
- The error message should appear like `This username already exist.`

**Comment by mail7** [comment]
Hi Kuldeep,

We updated Message in Mail7 core API and this issue now fixed and ready to use. and you may also visit our API docs [here](https://docs.mail7.io/mail-apis/get-email) .

**Comment by Kuldeep-Chhipa** [comment]
It's working fine now.
